server:
  port: 8082

spring:
  application:
    name: dafuweng-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler
  mapper-locations: classpath:system/mapper/*.xml
